package catalog

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"regexp"
	"slices"
	"strings"

	"gopkg.in/ini.v1"
)

// ErrNotFound is returned by FetchConf when the sysext does not exist in
// the queried repo (HTTP 404), letting callers distinguish "not in this
// repo" from transport or server failures.
var ErrNotFound = errors.New("sysext not found in catalog")

// GeneratedMarker is the first line prefix of every definition file
// written by catalog add. It is the ownership signal: add refuses to
// overwrite files that lack it, and remove refuses to delete them, so
// catalog operations can never clobber hand-written or package-shipped
// definitions that happen to share a name or component. The header also
// records the generating repo (see GeneratedRepo), which isolates two
// repos configured with the same Component from each other.
const GeneratedMarker = "# Generated by updex catalog"

// markerLine returns the full generated-file header for a repo.
func markerLine(repo Repo) string {
	return fmt.Sprintf("%s (repo: %s); managed by 'updex catalog'\n", GeneratedMarker, repo.Name)
}

// generatedRepoPattern extracts the generating repo name from a marker
// header line.
var generatedRepoPattern = regexp.MustCompile(`^` + regexp.QuoteMeta(GeneratedMarker) + ` \(repo: ([a-zA-Z0-9_-]+)\)`)

// maxMarkerLen bounds how much of a file is read to find the header.
const maxMarkerLen = 256

// IsGenerated reports whether data starts with the GeneratedMarker header.
func IsGenerated(data []byte) bool {
	return bytes.HasPrefix(data, []byte(GeneratedMarker))
}

// GeneratedRepo returns the catalog repo named in data's marker header.
// ok is false when data was not generated by catalog add.
func GeneratedRepo(data []byte) (repo string, ok bool) {
	m := generatedRepoPattern.FindSubmatch(data)
	if m == nil {
		return "", false
	}
	return string(m[1]), true
}

// GeneratedFileRepo returns the catalog repo named in the marker header of
// the file at path. ok is false when the file is missing, unreadable, or
// was not generated by catalog add.
func GeneratedFileRepo(path string) (repo string, ok bool) {
	f, err := os.Open(path)
	if err != nil {
		return "", false
	}
	defer func() { _ = f.Close() }()
	buf := make([]byte, maxMarkerLen)
	n, _ := io.ReadFull(f, buf)
	return GeneratedRepo(buf[:n])
}

// IsGeneratedFile reports whether the file at path was generated by
// catalog add, regardless of which repo generated it. Callers that act on
// a specific repo's files must compare GeneratedFileRepo instead.
func IsGeneratedFile(path string) bool {
	_, ok := GeneratedFileRepo(path)
	return ok
}

// sysextNamePattern matches safe sysext names: a single path/URL component
// that cannot traverse directories or hide as a dotfile. Covers every name
// the fedora-sysexts catalog publishes (e.g. "1password-cli",
// "nvidia-driver-cuda-580.95.05", "kubernetes-cri-o-1.32").
var sysextNamePattern = regexp.MustCompile(`^[a-zA-Z0-9_][a-zA-Z0-9._+-]*$`)

// ValidateSysextName rejects names that are not safe to use as a single
// filename component and URL path segment.
func ValidateSysextName(name string) error {
	if !sysextNamePattern.MatchString(name) {
		return fmt.Errorf("invalid sysext name %q", name)
	}
	return nil
}

// maxFetchSize bounds catalog HTTP response bodies; .conf files and
// contents-API listings are a few KB.
const maxFetchSize = 4 << 20

// nonSysextDirs are top-level repo directories that never hold a sysext.
var nonSysextDirs = []string{"docs", "LICENSES"}

// contentsEntry is the subset of a GitHub contents API entry List needs.
type contentsEntry struct {
	Name string `json:"name"`
	Type string `json:"type"`
}

// List enumerates the sysexts available in repo via its ListURL (a GitHub
// contents API endpoint): top-level directories minus dotted names and
// known non-sysext directories, sorted. When the GITHUB_TOKEN environment
// variable is set it is sent as a bearer token to raise the API rate limit.
// List always fetches live; see CachedList for the TTL+ETag cached variant.
func List(ctx context.Context, client *http.Client, repo Repo) ([]string, error) {
	names, _, _, err := fetchList(ctx, client, repo, "")
	return names, err
}

// fetchList performs the ListURL request. When etag is non-empty it is sent
// as If-None-Match; a 304 Not Modified response — which GitHub does not
// count against the API rate limit — returns notModified=true with no
// names. newETag carries the response's ETag header for cache storage.
func fetchList(ctx context.Context, client *http.Client, repo Repo, etag string) (names []string, newETag string, notModified bool, err error) {
	if repo.ListURL == "" {
		return nil, "", false, fmt.Errorf("catalog %q has no ListURL configured", repo.Name)
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodGet, repo.ListURL, nil)
	if err != nil {
		return nil, "", false, fmt.Errorf("failed to create list request: %w", err)
	}
	req.Header.Set("Accept", "application/vnd.github+json")
	if token := os.Getenv("GITHUB_TOKEN"); token != "" {
		req.Header.Set("Authorization", "Bearer "+token)
	}
	if etag != "" {
		req.Header.Set("If-None-Match", etag)
	}

	resp, err := client.Do(req)
	if err != nil {
		return nil, "", false, fmt.Errorf("failed to list catalog %q: %w", repo.Name, err)
	}
	defer func() { _ = resp.Body.Close() }()

	switch {
	case resp.StatusCode == http.StatusNotModified:
		return nil, etag, true, nil
	case resp.StatusCode != http.StatusOK:
		return nil, "", false, fmt.Errorf("failed to list catalog %q: %s returned %s", repo.Name, repo.ListURL, resp.Status)
	}

	var entries []contentsEntry
	if err := json.NewDecoder(io.LimitReader(resp.Body, maxFetchSize)).Decode(&entries); err != nil {
		return nil, "", false, fmt.Errorf("failed to decode catalog %q listing: %w", repo.Name, err)
	}

	for _, e := range entries {
		if e.Type != "dir" || strings.HasPrefix(e.Name, ".") || slices.Contains(nonSysextDirs, e.Name) {
			continue
		}
		names = append(names, e.Name)
	}
	slices.Sort(names)

	return names, resp.Header.Get("ETag"), false, nil
}

// FetchConf downloads the catalog-published sysupdate transfer definition
// for a sysext (<SiteURL>/<name>/<name>.conf). A 404 is reported as
// ErrNotFound.
func FetchConf(ctx context.Context, client *http.Client, repo Repo, name string) ([]byte, error) {
	if err := ValidateSysextName(name); err != nil {
		return nil, err
	}
	url := fmt.Sprintf("%s/%s/%s.conf", repo.SiteURL, name, name)

	req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create conf request: %w", err)
	}

	resp, err := client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch %s: %w", url, err)
	}
	defer func() { _ = resp.Body.Close() }()

	switch {
	case resp.StatusCode == http.StatusNotFound:
		return nil, fmt.Errorf("%q in catalog %q: %w", name, repo.Name, ErrNotFound)
	case resp.StatusCode != http.StatusOK:
		return nil, fmt.Errorf("failed to fetch %s: %s", url, resp.Status)
	}

	data, err := io.ReadAll(io.LimitReader(resp.Body, maxFetchSize))
	if err != nil {
		return nil, fmt.Errorf("failed to read %s: %w", url, err)
	}

	return data, nil
}

// RenderTransfer turns a catalog-published .conf into the .transfer content
// updex writes to a component directory. It prepends the GeneratedMarker
// ownership header, injects Features=<name> so the transfer is tied to its
// generated feature, and drops Target CurrentSymlink: updex manages the
// /var/lib/extensions link itself (see updex.installTransfer) and actively
// removes legacy current symlinks. Everything else — including %w/%a
// specifiers, which must stay unexpanded so the file remains valid across
// Fedora release upgrades — is preserved byte-for-byte, so the result
// diffs against the catalog original by exactly those three changes.
func RenderTransfer(conf []byte, repo Repo, name string) ([]byte, error) {
	cfg, err := ini.Load(conf)
	if err != nil {
		return nil, fmt.Errorf("failed to parse catalog conf: %w", err)
	}
	if _, err := cfg.GetSection("Source"); err != nil {
		return nil, fmt.Errorf("catalog conf has no [Source] section")
	}
	if _, err := cfg.GetSection("Target"); err != nil {
		return nil, fmt.Errorf("catalog conf has no [Target] section")
	}

	featuresLine := "Features=" + name
	var out bytes.Buffer
	out.Grow(len(conf) + len(featuresLine) + 64)
	out.WriteString(markerLine(repo))

	section := ""
	inserted := false
	for line := range strings.Lines(string(conf)) {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "[") && strings.HasSuffix(trimmed, "]") {
			section = trimmed[1 : len(trimmed)-1]
			out.WriteString(line)
			if section == "Transfer" && !inserted {
				if !strings.HasSuffix(line, "\n") {
					out.WriteByte('\n')
				}
				out.WriteString(featuresLine + "\n")
				inserted = true
			}
			continue
		}
		switch section {
		case "Target":
			if iniKeyOf(trimmed) == "CurrentSymlink" {
				continue
			}
		case "Transfer":
			if iniKeyOf(trimmed) == "Features" {
				continue // replaced by the injected line
			}
		}
		out.WriteString(line)
	}
	if !inserted {
		if !bytes.HasSuffix(out.Bytes(), []byte("\n")) {
			out.WriteByte('\n')
		}
		out.WriteString("\n[Transfer]\n" + featuresLine + "\n")
	}

	return out.Bytes(), nil
}

// iniKeyOf returns the key name of an INI "Key=value" line (whitespace
// around '=' tolerated), or "" for comments, section headers, and blanks.
func iniKeyOf(trimmedLine string) string {
	if trimmedLine == "" || strings.HasPrefix(trimmedLine, "#") || strings.HasPrefix(trimmedLine, ";") {
		return ""
	}
	key, _, found := strings.Cut(trimmedLine, "=")
	if !found {
		return ""
	}
	return strings.TrimSpace(key)
}

// RenderFeature builds the .feature content for a catalog sysext, headed
// by the GeneratedMarker ownership line. The base file is disabled;
// enabling happens through the standard drop-in written by EnableFeature,
// so later enable/disable cycles work exactly like any hand-written
// feature.
func RenderFeature(repo Repo, name string) []byte {
	return fmt.Appendf(nil,
		"%s[Feature]\nDescription=%s sysext from the %s catalog\nDocumentation=%s/%s/\nEnabled=false\n",
		markerLine(repo), name, repo.Name, repo.SiteURL, name)
}
