package catalog

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"strings"
	"unicode"

	"gopkg.in/ini.v1"
)

// ErrNotFound is returned by FetchConf when the sysext does not exist in
// the queried repo (HTTP 404), letting callers distinguish "not in this
// repo" from transport or server failures.
var ErrNotFound = errors.New("sysext not found in catalog")

// GeneratedMarker is the first line prefix of every definition file
// written by catalog add. It is the ownership signal: add refuses to
// overwrite files that lack it, and remove refuses to delete them, so
// catalog operations can never clobber hand-written or package-shipped
// definitions that happen to share a name or component. The header also
// records the generating repo (see GeneratedRepo), which isolates two
// repos configured with the same Component from each other.
const GeneratedMarker = "# Generated by updex catalog"

// markerLine returns the full generated-file header for a repo.
func markerLine(repo Repo) string {
	return fmt.Sprintf("%s (repo: %s); managed by 'updex catalog'\n", GeneratedMarker, repo.Name)
}

// generatedRepoPattern extracts the generating repo name from a marker
// header line.
var generatedRepoPattern = regexp.MustCompile(`^` + regexp.QuoteMeta(GeneratedMarker) + ` \(repo: ([a-zA-Z0-9_-]+)\)`)

// maxMarkerLen bounds how much of a file is read to find the header.
const maxMarkerLen = 256

// IsGenerated reports whether data starts with the GeneratedMarker header.
func IsGenerated(data []byte) bool {
	return bytes.HasPrefix(data, []byte(GeneratedMarker))
}

// GeneratedRepo returns the catalog repo named in data's marker header.
// ok is false when data was not generated by catalog add.
func GeneratedRepo(data []byte) (repo string, ok bool) {
	m := generatedRepoPattern.FindSubmatch(data)
	if m == nil {
		return "", false
	}
	return string(m[1]), true
}

// GeneratedFileRepo returns the catalog repo named in the marker header of
// the file at path. ok is false when the file is missing, unreadable, or
// was not generated by catalog add.
func GeneratedFileRepo(path string) (repo string, ok bool) {
	f, err := os.Open(path)
	if err != nil {
		return "", false
	}
	defer func() { _ = f.Close() }()
	buf := make([]byte, maxMarkerLen)
	n, _ := io.ReadFull(f, buf)
	return GeneratedRepo(buf[:n])
}

// IsGeneratedFile reports whether the file at path was generated by
// catalog add, regardless of which repo generated it. Callers that act on
// a specific repo's files must compare GeneratedFileRepo instead.
func IsGeneratedFile(path string) bool {
	_, ok := GeneratedFileRepo(path)
	return ok
}

// sysextNamePattern matches safe sysext names: a single path/URL component
// that cannot traverse directories or hide as a dotfile. Covers every name
// the fedora-sysexts catalog publishes (e.g. "1password-cli",
// "nvidia-driver-cuda-580.95.05", "kubernetes-cri-o-1.32").
var sysextNamePattern = regexp.MustCompile(`^[a-zA-Z0-9_][a-zA-Z0-9._+-]*$`)

// ValidateSysextName rejects names that are not safe to use as a single
// filename component and URL path segment.
func ValidateSysextName(name string) error {
	if !sysextNamePattern.MatchString(name) {
		return fmt.Errorf("invalid sysext name %q", name)
	}
	return nil
}

// maxFetchSize bounds catalog HTTP response bodies; .conf files and
// contents-API listings are a few KB.
const maxFetchSize = 4 << 20

// TargetPath is the trusted staging directory used for catalog transfers.
// Catalog metadata cannot override it. SDK callers should inject this value
// via updex.RuntimePaths rather than mutating this variable; it remains for
// compatibility wrappers and tests that have not yet migrated.
const defaultTargetPath = "/var/lib/extensions.d"

var TargetPath = defaultTargetPath

// nonSysextDirs are top-level repo directories that never hold a sysext.
var nonSysextDirs = []string{"docs", "LICENSES"}

// contentsEntry is the subset of a GitHub contents API entry List needs.
type contentsEntry struct {
	Name string `json:"name"`
	Type string `json:"type"`
}

// List enumerates the sysexts available in repo via its ListURL (a GitHub
// contents API endpoint): top-level directories minus dotted names and
// known non-sysext directories, sorted. When the GITHUB_TOKEN environment
// variable is set it is sent as a bearer token to the public GitHub API
// origin to raise the API rate limit.
// List always fetches live; see CachedList for the TTL+ETag cached variant.
func List(ctx context.Context, client *http.Client, repo Repo) ([]string, error) {
	names, _, _, err := fetchList(ctx, client, repo, "")
	return names, err
}

func isTrustedGitHubAPIURL(requestURL *url.URL) bool {
	return strings.EqualFold(requestURL.Scheme, "https") &&
		strings.EqualFold(requestURL.Hostname(), "api.github.com") &&
		(requestURL.Port() == "" || requestURL.Port() == "443")
}

func doListRequest(client *http.Client, req *http.Request) (*http.Response, error) {
	redirectSafeClient := *client
	previousCheckRedirect := client.CheckRedirect
	redirectSafeClient.CheckRedirect = func(redirectReq *http.Request, via []*http.Request) error {
		if previousCheckRedirect != nil {
			if err := previousCheckRedirect(redirectReq, via); err != nil {
				return err
			}
		} else if len(via) >= 10 {
			return errors.New("stopped after 10 redirects")
		}
		if !isTrustedGitHubAPIURL(redirectReq.URL) {
			redirectReq.Header.Del("Authorization")
		}
		return nil
	}
	return redirectSafeClient.Do(req)
}

// fetchList performs the ListURL request. When etag is non-empty it is sent
// as If-None-Match; a 304 Not Modified response — which GitHub does not
// count against the API rate limit — returns notModified=true with no
// names. newETag carries the response's ETag header for cache storage.
func fetchList(ctx context.Context, client *http.Client, repo Repo, etag string) (names []string, newETag string, notModified bool, err error) {
	if repo.ListURL == "" {
		return nil, "", false, fmt.Errorf("catalog %q has no ListURL configured", repo.Name)
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodGet, repo.ListURL, nil)
	if err != nil {
		return nil, "", false, fmt.Errorf("failed to create list request: %w", err)
	}
	req.Header.Set("Accept", "application/vnd.github+json")
	if token := os.Getenv("GITHUB_TOKEN"); token != "" && isTrustedGitHubAPIURL(req.URL) {
		req.Header.Set("Authorization", "Bearer "+token)
	}
	if etag != "" {
		req.Header.Set("If-None-Match", etag)
	}

	resp, err := doListRequest(client, req)
	if err != nil {
		return nil, "", false, fmt.Errorf("failed to list catalog %q: %w", repo.Name, err)
	}
	defer func() { _ = resp.Body.Close() }()

	switch {
	case resp.StatusCode == http.StatusNotModified:
		return nil, etag, true, nil
	case resp.StatusCode != http.StatusOK:
		return nil, "", false, fmt.Errorf("failed to list catalog %q: %s returned %s", repo.Name, repo.ListURL, resp.Status)
	}

	var entries []contentsEntry
	if err := json.NewDecoder(io.LimitReader(resp.Body, maxFetchSize)).Decode(&entries); err != nil {
		return nil, "", false, fmt.Errorf("failed to decode catalog %q listing: %w", repo.Name, err)
	}

	for _, e := range entries {
		if e.Type != "dir" || strings.HasPrefix(e.Name, ".") || slices.Contains(nonSysextDirs, e.Name) {
			continue
		}
		names = append(names, e.Name)
	}
	slices.Sort(names)

	return names, resp.Header.Get("ETag"), false, nil
}

// FetchConf downloads the catalog-published sysupdate transfer definition
// for a sysext (<SiteURL>/<name>/<name>.conf). A 404 is reported as
// ErrNotFound.
func FetchConf(ctx context.Context, client *http.Client, repo Repo, name string) ([]byte, error) {
	if err := ValidateSysextName(name); err != nil {
		return nil, err
	}
	url := fmt.Sprintf("%s/%s/%s.conf", repo.SiteURL, name, name)

	req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create conf request: %w", err)
	}

	resp, err := client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch %s: %w", url, err)
	}
	defer func() { _ = resp.Body.Close() }()

	switch {
	case resp.StatusCode == http.StatusNotFound:
		return nil, fmt.Errorf("%q in catalog %q: %w", name, repo.Name, ErrNotFound)
	case resp.StatusCode != http.StatusOK:
		return nil, fmt.Errorf("failed to fetch %s: %s", url, resp.Status)
	}

	data, err := io.ReadAll(io.LimitReader(resp.Body, maxFetchSize))
	if err != nil {
		return nil, fmt.Errorf("failed to read %s: %w", url, err)
	}

	return data, nil
}

// RenderTransferTo turns a catalog-published .conf into the .transfer content
// updex writes to a component directory. It behaves like RenderTransfer but
// uses the given targetPath instead of the package-global TargetPath.
// This is the explicit-path variant used by SDK internals.
func RenderTransferTo(conf []byte, repo Repo, name string, targetPath string) ([]byte, error) {
	cfg, err := ini.Load(conf)
	if err != nil {
		return nil, fmt.Errorf("failed to parse catalog conf: %w", err)
	}
	source, err := cfg.GetSection("Source")
	if err != nil {
		return nil, fmt.Errorf("catalog conf has no [Source] section")
	}
	target, err := cfg.GetSection("Target")
	if err != nil {
		return nil, fmt.Errorf("catalog conf has no [Target] section")
	}
	if err := validateCatalogPatternEncoding(conf); err != nil {
		return nil, err
	}
	if err := validateCatalogTransferTo(source, target, repo, name, targetPath); err != nil {
		return nil, err
	}

	featuresLine := "Features=" + name
	sourcePattern := source.Key("MatchPattern").String()
	targetPattern := target.Key("MatchPattern").String()
	var out bytes.Buffer
	out.Grow(len(conf) + len(featuresLine) + 64)
	out.WriteString(markerLine(repo))

	section := ""
	inserted := false
	// gopkg.in/ini.v1 lets a value span several lines when it opens with `"""`
	// or a backtick whose match is not on the same line, or when its trimmed
	// value ends in a backslash. Every line in one of those blocks is value
	// body, not a key, comment, or section header, so it must be passed through
	// verbatim — the keyless-line guard below would otherwise delete it and
	// leave a value incomplete. When the key that opened the value is one we
	// strip (Features/Verify) or lives in a rewritten section, the whole block
	// is dropped instead, so no body line survives as stray top-level text.
	multilineQuote := ""
	multilineDropped := false
	continuationOpen := false
	continuationDropped := false
	for line := range strings.Lines(string(conf)) {
		trimmed := strings.TrimSpace(line)
		if multilineQuote != "" {
			if iniMultilineCloses(line, multilineQuote) {
				multilineQuote = ""
			}
			if multilineDropped {
				continue
			}
			out.WriteString(line)
			continue
		}
		if continuationOpen {
			dropped := continuationDropped
			if iniContinuationCloses(line) {
				continuationOpen = false
				continuationDropped = false
			}
			if dropped {
				continue
			}
			out.WriteString(line)
			continue
		}
		if parsedSection, ok, err := parseSectionHeader(trimmed); err != nil {
			return nil, err
		} else if ok {
			section = parsedSection
			out.WriteString(line)
			switch section {
			case "transfer":
				if !strings.HasSuffix(line, "\n") {
					out.WriteByte('\n')
				}
				if !inserted {
					out.WriteString(featuresLine + "\n")
					inserted = true
				}
			case "source":
				if !strings.HasSuffix(line, "\n") {
					out.WriteByte('\n')
				}
				fmt.Fprintf(&out, "Type=url-file\nPath=%s/%s/\nMatchPattern=%s\n",
					strings.TrimRight(repo.SiteURL, "/"), name, sourcePattern)
			case "target":
				if !strings.HasSuffix(line, "\n") {
					out.WriteByte('\n')
				}
				fmt.Fprintf(&out, "Type=regular-file\nPath=%s\nMatchPattern=%s\nMode=0644\n",
					targetPath, targetPattern)
			}
			continue
		}
		key := strings.ToLower(iniKeyOf(trimmed))
		drop := false
		switch section {
		case "source", "target":
			drop = true // rewritten wholesale above
		case "transfer":
			switch {
			case key == "features":
				drop = true // replaced by the injected line
			case key == "verify":
				drop = true // catalog input must not disable GPG verification; the absent-key default (true) applies
			case key == "" && trimmed != "" && !strings.HasPrefix(trimmed, "#") && !strings.HasPrefix(trimmed, ";"):
				drop = true // key could not be unambiguously parsed; drop rather than risk a disguised Verify/Features override
			}
		}
		// Track an opened multiline value even in a dropped section, so its
		// body cannot be mistaken for a section header or a top-level key.
		if quote := iniMultilineOpen(line); quote != "" {
			multilineQuote = quote
			multilineDropped = drop
		} else if iniContinuationOpen(line) {
			continuationOpen = true
			continuationDropped = drop
		}
		if drop {
			continue
		}
		out.WriteString(line)
	}
	if !inserted {
		if !bytes.HasSuffix(out.Bytes(), []byte("\n")) {
			out.WriteByte('\n')
		}
		out.WriteString("\n[Transfer]\n" + featuresLine + "\n")
	}

	return out.Bytes(), nil
}

// RenderTransfer turns a catalog-published .conf into the .transfer content
// updex writes to a component directory. It prepends the GeneratedMarker
// ownership header, injects Features=<name> so the transfer is tied to its
// generated feature. Security-sensitive fields are validated and rewritten:
// the source stays under the configured catalog, and the target is a regular
// 0644 file under /var/lib/extensions.d. Other content, including %w/%a
// specifiers, is preserved byte-for-byte.
func RenderTransfer(conf []byte, repo Repo, name string) ([]byte, error) {
	return RenderTransferTo(conf, repo, name, TargetPath)
}

func validateCatalogPatternEncoding(conf []byte) error {
	section := ""
	for line := range strings.Lines(string(conf)) {
		trimmed := strings.TrimSpace(line)
		if parsedSection, ok, err := parseSectionHeader(trimmed); err != nil {
			return err
		} else if ok {
			section = parsedSection
			continue
		}
		if section != "source" && section != "target" {
			continue
		}
		separator := strings.IndexAny(trimmed, "=:")
		if separator < 0 || !strings.EqualFold(strings.TrimSpace(trimmed[:separator]), "MatchPattern") {
			continue
		}
		if strings.ContainsAny(trimmed[separator+1:], "\"'\\") {
			return fmt.Errorf("catalog conf %s.MatchPattern must use unquoted filenames", strings.ToUpper(section[:1])+section[1:])
		}
	}
	return nil
}

func parseSectionHeader(line string) (name string, ok bool, err error) {
	if !strings.HasPrefix(line, "[") {
		return "", false, nil
	}
	end := strings.IndexByte(line, ']')
	if end < 0 {
		return "", false, fmt.Errorf("catalog conf contains an unsupported section header")
	}
	trailing := strings.TrimSpace(line[end+1:])
	if trailing != "" && !strings.HasPrefix(trailing, "#") && !strings.HasPrefix(trailing, ";") {
		return "", false, fmt.Errorf("catalog conf contains an unsupported section header")
	}
	name = strings.ToLower(strings.TrimSpace(line[1:end]))
	if name == "" {
		return "", false, fmt.Errorf("catalog conf contains an empty section header")
	}
	return name, true, nil
}

func validateCatalogTransferTo(source, target *ini.Section, repo Repo, name string, targetPath string) error {
	sourceType, err := source.GetKey("Type")
	if err != nil || sourceType.String() != "url-file" {
		return fmt.Errorf("catalog conf Source.Type must be url-file")
	}

	sourcePath, err := source.GetKey("Path")
	if err != nil {
		return fmt.Errorf("catalog conf Source.Path is required")
	}
	expectedSource := strings.TrimRight(repo.SiteURL, "/") + "/" + name
	if strings.TrimRight(sourcePath.String(), "/") != expectedSource {
		return fmt.Errorf("catalog conf Source.Path must be %s/", expectedSource)
	}

	if err := validateCatalogPatterns(source, "Source"); err != nil {
		return err
	}
	if err := validateCatalogPatterns(target, "Target"); err != nil {
		return err
	}

	if targetType, err := target.GetKey("Type"); err == nil && targetType.String() != "regular-file" {
		return fmt.Errorf("catalog conf Target.Type must be regular-file")
	}
	if tp, err := target.GetKey("Path"); err == nil {
		got := filepath.Clean(tp.String())
		if got != filepath.Clean(targetPath) && got != defaultTargetPath {
			return fmt.Errorf("catalog conf Target.Path must be %s", defaultTargetPath)
		}
	}
	if relative, err := target.GetKey("PathRelativeTo"); err == nil && relative.String() != "" {
		return fmt.Errorf("catalog conf Target.PathRelativeTo is not supported")
	}

	return nil
}

func validateCatalogPatterns(section *ini.Section, sectionName string) error {
	key, err := section.GetKey("MatchPattern")
	if err != nil {
		return fmt.Errorf("catalog conf %s.MatchPattern is required", sectionName)
	}
	value := key.String()
	if strings.ContainsAny(value, "\r\n\x00\"'") {
		return fmt.Errorf("catalog conf %s.MatchPattern must contain filenames only", sectionName)
	}
	patterns := strings.Fields(value)
	if len(patterns) == 0 {
		return fmt.Errorf("catalog conf %s.MatchPattern is required", sectionName)
	}
	for _, pattern := range patterns {
		if pattern == "." || pattern == ".." || filepath.Base(pattern) != pattern || strings.ContainsRune(pattern, '\\') {
			return fmt.Errorf("catalog conf %s.MatchPattern must contain filenames only", sectionName)
		}
	}
	return nil
}

// iniKeyOf returns the key name of an INI "Key=value" line (whitespace
// around the delimiter tolerated), or "" for comments, section headers, and
// blanks. It mirrors gopkg.in/ini.v1's default key parsing so a key spelling
// the ini parser accepts cannot slip past a stricter check here: both
// default key/value delimiters ('=' and ':', whichever comes first) and a
// key name wrapped in matching backticks or double quotes.
func iniKeyOf(trimmedLine string) string {
	if trimmedLine == "" || strings.HasPrefix(trimmedLine, "#") || strings.HasPrefix(trimmedLine, ";") {
		return ""
	}

	var keyQuote string
	switch {
	case trimmedLine[0] == '"' && len(trimmedLine) > 6 && trimmedLine[0:3] == `"""`:
		keyQuote = `"""`
	case trimmedLine[0] == '"':
		keyQuote = `"`
	case trimmedLine[0] == '`':
		keyQuote = "`"
	}
	if keyQuote != "" {
		closeIdx := strings.Index(trimmedLine[len(keyQuote):], keyQuote)
		if closeIdx < 0 {
			return ""
		}
		return strings.TrimSpace(trimmedLine[len(keyQuote) : len(keyQuote)+closeIdx])
	}

	idx := strings.IndexAny(trimmedLine, "=:")
	if idx <= 0 {
		return ""
	}
	return strings.TrimSpace(trimmedLine[:idx])
}

// iniMultilineOpen reports the quote that leaves a gopkg.in/ini.v1 value open
// past the end of this line, or "" when the line closes (or never opens) one.
// It mirrors ini.v1's readValue: a value beginning with `"""` or a backtick
// runs until the next occurrence of that same quote, which may be several
// lines later.
//
// It takes the raw line, newline included, because that is what ini.v1's
// parser sees, and the length tests below are sensitive to it: a bare `"""`
// as a value opens a multiline only when a newline follows it.
func iniMultilineOpen(rawLine string) string {
	value, ok := iniValueOf(rawLine)
	if !ok {
		return ""
	}
	value = strings.TrimLeftFunc(value, unicode.IsSpace)

	var valQuote string
	switch {
	case len(value) > 3 && value[0:3] == `"""`:
		valQuote = `"""`
	case value != "" && value[0] == '`':
		valQuote = "`"
	default:
		return ""
	}
	if strings.Contains(value[len(valQuote):], valQuote) {
		return "" // closed on the same line
	}
	return valQuote
}

// iniMultilineCloses reports whether rawLine ends the open multiline value
// quoted by valQuote. It mirrors ini.v1's readMultilines, including its
// backslash-continuation escape, so a line this function calls closing is a
// line ini.v1 also treats as closing.
func iniMultilineCloses(rawLine, valQuote string) bool {
	pos := strings.LastIndex(rawLine, valQuote)
	if pos < 0 {
		return false
	}
	rest := strings.TrimRight(rawLine[pos+len(valQuote):], "\r\n")
	return !strings.HasSuffix(strings.TrimSpace(rest), `\`)
}

// iniContinuationOpen reports whether gopkg.in/ini.v1 treats the value on
// rawLine as opening a backslash continuation. Quoted values are excluded:
// readValue handles its triple-quote/backtick case before considering an
// ordinary continuation, even when text after a closing quote ends in `\`.
func iniContinuationOpen(rawLine string) bool {
	value, ok := iniValueOf(rawLine)
	if !ok {
		return false
	}
	value = strings.TrimSpace(value)
	if value == "" || strings.HasPrefix(value, `"""`) || strings.HasPrefix(value, "`") {
		return false
	}
	return strings.HasSuffix(value, `\`)
}

// iniContinuationCloses reports whether rawLine ends an open backslash
// continuation. ini.v1 consumes the line and stops when its trimmed form is
// empty or does not itself end in a backslash.
func iniContinuationCloses(rawLine string) bool {
	trimmed := strings.TrimSpace(rawLine)
	return trimmed == "" || !strings.HasSuffix(trimmed, `\`)
}

// iniValueOf returns the raw value portion of an INI "Key=value" line —
// everything after the delimiter, newline included — and whether the line has
// one at all. It mirrors gopkg.in/ini.v1's readKeyName offset so the value
// this reports is the value ini.v1 would parse. It is kept separate from
// iniKeyOf, which answers the different question of what the key is named and
// whose exact behavior the Verify/Features strip guard depends on.
func iniValueOf(rawLine string) (string, bool) {
	line := strings.TrimLeftFunc(rawLine, unicode.IsSpace)
	if line == "" || strings.HasPrefix(line, "#") || strings.HasPrefix(line, ";") {
		return "", false
	}

	var keyQuote string
	switch {
	case line[0] == '"' && len(line) > 6 && line[0:3] == `"""`:
		keyQuote = `"""`
	case line[0] == '"':
		keyQuote = `"`
	case line[0] == '`':
		keyQuote = "`"
	}
	if keyQuote != "" {
		startIdx := len(keyQuote)
		closeIdx := strings.Index(line[startIdx:], keyQuote)
		if closeIdx < 0 {
			return "", false
		}
		afterKey := startIdx + closeIdx + startIdx
		if afterKey > len(line) {
			return "", false
		}
		i := strings.IndexAny(line[afterKey:], "=:")
		if i < 0 {
			return "", false
		}
		return line[afterKey+i+1:], true
	}

	idx := strings.IndexAny(line, "=:")
	if idx <= 0 {
		return "", false
	}
	return line[idx+1:], true
}

// RenderFeature builds the .feature content for a catalog sysext, headed
// by the GeneratedMarker ownership line. The base file is disabled;
// enabling happens through the standard drop-in written by EnableFeature,
// so later enable/disable cycles work exactly like any hand-written
// feature.
//
// The description names the sysext only: the originating catalog is
// already reported in its own column by 'updex features list' (see
// FeatureInfo.Origin), so repeating it here is noise.
func RenderFeature(repo Repo, name string) []byte {
	return fmt.Appendf(nil,
		"%s[Feature]\nDescription=%s sysext\nDocumentation=%s/%s/\nEnabled=false\n",
		markerLine(repo), name, repo.SiteURL, name)
}
