// Package testutil provides test utilities for the updex project.
package testutil

import (
	"bytes"
	"fmt"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"testing"

	"github.com/ProtonMail/go-crypto/openpgp"

	"github.com/frostyard/updex/manifest"
)

// TestServerFiles configures the test HTTP server's responses.
type TestServerFiles struct {
	// Files maps filename to SHA256 hash (appears in SHA256SUMS manifest)
	Files map[string]string
	// Content maps filename to file content (for downloads)
	Content map[string][]byte
}

// NewTestServer creates an httptest.Server that serves SHA256SUMS manifest and files.
// The server serves:
//   - /SHA256SUMS - manifest with hash + filename entries
//   - /{filename} - file content from Content map
func NewTestServer(t *testing.T, files TestServerFiles) *httptest.Server {
	t.Helper()
	return httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		path := strings.TrimPrefix(r.URL.Path, "/")

		if path == "SHA256SUMS" {
			var lines []string
			for filename, hash := range files.Files {
				lines = append(lines, fmt.Sprintf("%s  %s", hash, filename))
			}
			_, _ = w.Write([]byte(strings.Join(lines, "\n")))
			return
		}

		if content, ok := files.Content[path]; ok {
			_, _ = w.Write(content)
			return
		}

		w.WriteHeader(http.StatusNotFound)
	}))
}

// signManifestKeyrings accumulates the OpenPGP entities generated by
// SignManifest per test, keyed by *testing.T, so a test that stands up
// several signed fixtures (e.g. two catalogs under separate keys) ends up
// with one keyring that trusts all of them rather than each call clobbering
// manifest.KeyringPaths out from under the others.
var signManifestKeyrings sync.Map // *testing.T -> *signManifestState

type signManifestState struct {
	mu       sync.Mutex
	path     string
	entities openpgp.EntityList
}

// SignManifest generates an ephemeral OpenPGP keypair, points
// manifest.KeyringPaths at a keyring trusting it (and any other key
// SignManifest generated earlier in the same test) for the rest of the test,
// and returns a detached signature over content. Callers serve the returned
// bytes at "<manifest-url>.gpg" so a Verify=true (the default) transfer
// downloading content as its manifest passes signature verification.
//
// Call SignManifest for every fixture before starting any goroutine that
// downloads concurrently: manifest.KeyringPaths is a single package-global
// var, so mutating it while another goroutine is reading it is a race.
func SignManifest(t *testing.T, content []byte) []byte {
	t.Helper()

	entity, err := openpgp.NewEntity("updex test", "", "test@example.com", nil)
	if err != nil {
		t.Fatalf("openpgp.NewEntity() error = %v", err)
	}

	stateIface, _ := signManifestKeyrings.LoadOrStore(t, &signManifestState{
		path: filepath.Join(t.TempDir(), "keyring.gpg"),
	})
	state := stateIface.(*signManifestState)

	state.mu.Lock()
	state.entities = append(state.entities, entity)
	var keyring bytes.Buffer
	for _, e := range state.entities {
		if err := e.Serialize(&keyring); err != nil {
			state.mu.Unlock()
			t.Fatalf("entity.Serialize() error = %v", err)
		}
	}
	if err := os.WriteFile(state.path, keyring.Bytes(), 0o600); err != nil {
		state.mu.Unlock()
		t.Fatalf("WriteFile(keyring) error = %v", err)
	}
	state.mu.Unlock()

	original := manifest.KeyringPaths
	manifest.KeyringPaths = []string{state.path}
	t.Cleanup(func() { manifest.KeyringPaths = original })

	var signature bytes.Buffer
	if err := openpgp.DetachSign(&signature, entity, bytes.NewReader(content), nil); err != nil {
		t.Fatalf("openpgp.DetachSign() error = %v", err)
	}
	return signature.Bytes()
}

// NewErrorServer creates a server that always returns the given status code.
func NewErrorServer(t *testing.T, statusCode int) *httptest.Server {
	t.Helper()
	return httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(statusCode)
	}))
}
